/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MSG_H_RPCGEN
#define _MSG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Data {
	int n_reqs;
	int n_hits;
};
typedef struct Data Data;

#define MESSAGEPROG 99
#define MESSAGEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HANDLEREQUEST 1
extern  char ** handlerequest_1(char **, CLIENT *);
extern  char ** handlerequest_1_svc(char **, struct svc_req *);
#define REPORTSTAT 2
extern  Data * reportstat_1(void *, CLIENT *);
extern  Data * reportstat_1_svc(void *, struct svc_req *);
extern int messageprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HANDLEREQUEST 1
extern  char ** handlerequest_1();
extern  char ** handlerequest_1_svc();
#define REPORTSTAT 2
extern  Data * reportstat_1();
extern  Data * reportstat_1_svc();
extern int messageprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Data (XDR *, Data*);

#else /* K&R C */
extern bool_t xdr_Data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MSG_H_RPCGEN */
