/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "msg.h"

bool_t
xdr_Data (XDR *xdrs, Data *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n_reqs))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n_hits))
		 return FALSE;
	return TRUE;
}
